Repository decred/dcrd, pull requests merged in 2024-09, with the labels that each got.

#3439 rpcserver: Remove wallet RPC stakepooluserinfo.
  internal/rpcserver/rpcserver.go
Labels: rpc server api change

#3442 secp256k1: Tighten max magnitudes in comments.
  dcrec/secp256k1/field.go
Labels: documentation

#3441 secp256k1: Return normalized val from DecompressY.
  dcrec/secp256k1/curve.go
  dcrec/secp256k1/curve_test.go
  dcrec/secp256k1/ecdsa/signature.go
  dcrec/secp256k1/pubkey.go
Labels: optimization
